var dir_12355877a0252cbe010b061dafe0cc72 =
[
    [ "Colourf.cpp", "_colourf_8cpp_source.html", null ],
    [ "Colourf.hpp", "_colourf_8hpp_source.html", null ],
    [ "ColourRamp.cpp", "_colour_ramp_8cpp_source.html", null ],
    [ "ColourRamp.hpp", "_colour_ramp_8hpp_source.html", null ],
    [ "Colouruc.cpp", "_colouruc_8cpp_source.html", null ],
    [ "Colouruc.hpp", "_colouruc_8hpp_source.html", null ],
    [ "CoreLib.hpp", "_core_lib_8hpp_source.html", null ],
    [ "Dimensions.cpp", "_dimensions_8cpp_source.html", null ],
    [ "Dimensions.hpp", "_dimensions_8hpp_source.html", null ],
    [ "Exceptions.cpp", "_exceptions_8cpp_source.html", null ],
    [ "Exceptions.hpp", "_exceptions_8hpp_source.html", null ],
    [ "Logging.cpp", "_logging_8cpp_source.html", null ],
    [ "Logging.hpp", "_logging_8hpp_source.html", null ],
    [ "Multithreading.cpp", "_multithreading_8cpp_source.html", null ],
    [ "Multithreading.hpp", "_multithreading_8hpp_source.html", null ],
    [ "Profiling.cpp", "_profiling_8cpp_source.html", null ],
    [ "Profiling.hpp", "_profiling_8hpp_source.html", null ],
    [ "Singleton.hpp", "_singleton_8hpp_source.html", null ],
    [ "StringUtils.cpp", "_string_utils_8cpp_source.html", null ],
    [ "StringUtils.hpp", "_string_utils_8hpp_source.html", null ],
    [ "TemplateManager.hpp", "_template_manager_8hpp_source.html", null ],
    [ "Timer.cpp", "_timer_8cpp_source.html", null ],
    [ "Timer.hpp", "_timer_8hpp_source.html", null ],
    [ "TimerMinimal.cpp", "_timer_minimal_8cpp_source.html", null ],
    [ "TimerMinimal.hpp", "_timer_minimal_8hpp_source.html", null ],
    [ "Utilities.cpp", "_utilities_8cpp_source.html", null ],
    [ "Utilities.hpp", "_utilities_8hpp_source.html", null ]
];